import { StyleSheet } from "@react-pdf/renderer";

export const COLORS = {
    background: "#050506",
    card: "#0f0f12",
    cardAlt: "#141418",
    border: "#232329",
    foreground: "#f5f5f7",
    muted: "#9a9aa2",
    mutedDark: "#6f6f78",
    accent: "#7c5cff",
    accent2: "#22d3ee",
    white: "#ffffff",
};

export const PAGE_PADDING = 46;

export const styles = StyleSheet.create({
    page: {
          backgroundColor: COLORS.background,
          color: COLORS.foreground,
          fontFamily: "Helvetica",
          paddingTop: PAGE_PADDING,
          paddingBottom: 60,
          paddingHorizontal: PAGE_PADDING,
          fontSize: 10.5,
    },
    coverPage: {
          backgroundColor: COLORS.background,
          color: COLORS.foreground,
          fontFamily: "Helvetica",
          paddingHorizontal: PAGE_PADDING,
          alignItems: "center",
          justifyContent: "center",
    },
    logoBadge: {
          width: 52,
          height: 52,
          borderRadius: 26,
          backgroundColor: COLORS.accent,
          alignItems: "center",
          justifyContent: "center",
          marginBottom: 22,
    },
    logoBadgeText: {
          color: COLORS.white,
          fontSize: 22,
          fontFamily: "Helvetica-Bold",
    },
    brandName: {
          fontSize: 12,
          letterSpacing: 3,
          color: COLORS.accent2,
          fontFamily: "Helvetica-Bold",
          marginBottom: 18,
          textAlign: "center",
    },
    coverTitle: {
          fontSize: 34,
          fontFamily: "Helvetica-Bold",
          color: COLORS.white,
          textAlign: "center",
          marginBottom: 14,
    },
    coverTagline: {
          fontSize: 13,
          color: COLORS.muted,
          textAlign: "center",
          marginBottom: 30,
    },
    coverDivider: {
          width: 60,
          height: 2,
          backgroundColor: COLORS.accent,
          marginBottom: 30,
    },
    coverFeatureRow: {
          flexDirection: "row",
          alignItems: "center",
          marginBottom: 10,
    },
    coverFeatureDot: {
          width: 5,
          height: 5,
          borderRadius: 2.5,
          backgroundColor: COLORS.accent2,
          marginRight: 8,
    },
    coverFeatureText: {
          fontSize: 11.5,
          color: COLORS.foreground,
    },
    coverFooterText: {
          position: "absolute",
          bottom: 40,
          fontSize: 8.5,
          color: COLORS.mutedDark,
          textAlign: "center",
          width: "100%",
          left: 0,
    },
    eyebrow: {
          fontSize: 9,
          letterSpacing: 2,
          fontFamily: "Helvetica-Bold",
          color: COLORS.accent2,
          marginBottom: 8,
    },
    h1: {
          fontSize: 22,
          fontFamily: "Helvetica-Bold",
          color: COLORS.white,
          marginBottom: 10,
    },
    h2: {
          fontSize: 15,
          fontFamily: "Helvetica-Bold",
          color: COLORS.white,
          marginBottom: 4,
    },
    subtitle: {
          fontSize: 11,
          color: COLORS.muted,
          marginBottom: 18,
    },
    bodyText: {
          fontSize: 10.5,
          color: COLORS.foreground,
          lineHeight: 1.6,
          marginBottom: 12,
    },
    mutedText: {
          fontSize: 9.5,
          color: COLORS.muted,
          lineHeight: 1.5,
    },
    divider: {
          height: 1,
          backgroundColor: COLORS.border,
          marginVertical: 16,
    },
    card: {
          backgroundColor: COLORS.card,
          borderWidth: 1,
          borderColor: COLORS.border,
          borderRadius: 10,
          padding: 14,
          marginBottom: 12,
    },
    cardRow: {
          flexDirection: "row",
    },
    accentBar: {
          width: 3,
          borderRadius: 2,
          backgroundColor: COLORS.accent2,
          marginRight: 12,
    },
    cardContent: {
          flex: 1,
    },
    cardTitleRow: {
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "space-between",
          marginBottom: 6,
    },
    cardTitle: {
          fontSize: 12.5,
          fontFamily: "Helvetica-Bold",
          color: COLORS.white,
    },
    cardIndex: {
          fontSize: 8.5,
          color: COLORS.mutedDark,
          fontFamily: "Helvetica-Bold",
    },
    labelTag: {
          fontSize: 7.5,
          letterSpacing: 1.5,
          fontFamily: "Helvetica-Bold",
          color: COLORS.accent2,
          marginBottom: 3,
    },
    promptText: {
          fontSize: 9.5,
          color: COLORS.foreground,
          lineHeight: 1.5,
          marginBottom: 8,
    },
    useWhenText: {
          fontSize: 9,
          color: COLORS.muted,
          lineHeight: 1.4,
    },
    tagPill: {
          borderWidth: 1,
          borderColor: COLORS.accent,
          borderRadius: 20,
          paddingHorizontal: 10,
          paddingVertical: 3,
          marginBottom: 16,
          alignSelf: "flex-start",
    },
    tagPillText: {
          fontSize: 8.5,
          color: COLORS.accent2,
          fontFamily: "Helvetica-Bold",
          letterSpacing: 1,
    },
    stepRow: {
          flexDirection: "row",
          marginBottom: 14,
    },
    stepBadge: {
          width: 26,
          height: 26,
          borderRadius: 13,
          backgroundColor: COLORS.accent,
          alignItems: "center",
          justifyContent: "center",
          marginRight: 12,
    },
    stepBadgeText: {
          fontSize: 11,
          fontFamily: "Helvetica-Bold",
          color: COLORS.white,
    },
    stepContent: {
          flex: 1,
          paddingTop: 2,
    },
    stepTitle: {
          fontSize: 11.5,
          fontFamily: "Helvetica-Bold",
          color: COLORS.white,
          marginBottom: 3,
    },
    stepText: {
          fontSize: 9.5,
          color: COLORS.muted,
          lineHeight: 1.45,
    },
    bulletRow: {
          flexDirection: "row",
          alignItems: "flex-start",
          marginBottom: 6,
    },
    bulletDot: {
          width: 4,
          height: 4,
          borderRadius: 2,
          backgroundColor: COLORS.accent2,
          marginRight: 8,
          marginTop: 4,
    },
    bulletText: {
          fontSize: 9.5,
          color: COLORS.foreground,
          flex: 1,
          lineHeight: 1.45,
    },
    proTipBox: {
          backgroundColor: COLORS.cardAlt,
          borderWidth: 1,
          borderColor: COLORS.border,
          borderRadius: 8,
          padding: 10,
          marginTop: 10,
    },
    proTipLabel: {
          fontSize: 8,
          fontFamily: "Helvetica-Bold",
          color: COLORS.accent,
          marginBottom: 3,
          letterSpacing: 1,
    },
    proTipText: {
          fontSize: 9,
          color: COLORS.muted,
          lineHeight: 1.4,
    },
    toolCard: {
          backgroundColor: COLORS.card,
          borderWidth: 1,
          borderColor: COLORS.border,
          borderRadius: 10,
          padding: 12,
          marginBottom: 10,
    },
    toolBadge: {
          width: 22,
          height: 22,
          borderRadius: 6,
          backgroundColor: COLORS.accent2,
          alignItems: "center",
          justifyContent: "center",
          marginRight: 10,
    },
    toolBadgeText: {
          fontSize: 10,
          fontFamily: "Helvetica-Bold",
          color: COLORS.background,
    },
    toolName: {
          fontSize: 12,
          fontFamily: "Helvetica-Bold",
          color: COLORS.white,
    },
    toolMetaLabel: {
          fontSize: 7.5,
          letterSpacing: 1,
          fontFamily: "Helvetica-Bold",
          color: COLORS.mutedDark,
          marginTop: 5,
    },
    toolMetaText: {
          fontSize: 9,
          color: COLORS.muted,
          lineHeight: 1.4,
    },
    bonusHighlightBox: {
          backgroundColor: COLORS.cardAlt,
          borderWidth: 1,
          borderColor: COLORS.accent,
          borderRadius: 10,
          padding: 16,
          marginBottom: 16,
    },
    bonusLabel: {
          fontSize: 8.5,
          letterSpacing: 1.5,
          fontFamily: "Helvetica-Bold",
          color: COLORS.accent2,
          marginBottom: 4,
    },
    bonusValue: {
          fontSize: 14,
          fontFamily: "Helvetica-Bold",
          color: COLORS.white,
          marginBottom: 10,
    },
    ctaPill: {
          backgroundColor: COLORS.accent,
          borderRadius: 20,
          paddingVertical: 8,
          paddingHorizontal: 16,
          alignSelf: "flex-start",
          marginTop: 4,
    },
    ctaPillText: {
          fontSize: 9.5,
          fontFamily: "Helvetica-Bold",
          color: COLORS.white,
    },
    footer: {
          position: "absolute",
          bottom: 26,
          left: PAGE_PADDING,
          right: PAGE_PADDING,
          flexDirection: "row",
          justifyContent: "space-between",
          alignItems: "center",
    },
    footerText: {
          fontSize: 7.5,
          color: COLORS.mutedDark,
    },
    footerPage: {
          fontSize: 7.5,
          color: COLORS.mutedDark,
    },
});
